### ISSUE TITLE
config.json not found for SD 1.5

### ISSUE THREAD

**Issue by Haozong-Zeng** [neverbiasu/ComfyUI-StyleShot#4]
Thanks for the great work!

When trying to use the ComfyUI version, I am not able to run the demo because of the following error:

> OSError: Error no file named config.json found in directory /home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/prtrained_models/stable-diffusion-v1-5-archive.

I am using python 3.8 as in the original StyleShot enviroment and install all the requirements in both repositories (origin + ComfyUI).

Could you help me with that?

**Comment by neverbiasu** [comment]
Because ComfyOrg/stable-diffusion-v1-5-archive don't have config file. I will find another sd15 repo which include model config.

**Comment by Haozong-Zeng** [comment]
Hi, I tried to use other sd15 repo like benjamin-paine/stable-diffusion-v1-5 and fix some dependency conflicts (e.g. torchvision.transforms.functional) loading from ComfyUI/custom_nodes/ComfyUI-StyleShot/prtrained_models but got an error saying that:

> AttributeError: 'ControlNetModel' object has no attribute 'nets'

debug info:

> The attributes of controlnet are: ['T_destination', '_automatically_saved_args', '_backward_hooks', '_backward_pre_hooks', '_buffers', '_compiled_call_impl', '_deprecated_kwargs', '_forward_hooks', '_forward_hooks_always_called', '_forward_hooks_with_kwargs', '_forward_pre_hooks', '_forward_pre_hooks_with_kwargs', '_internal_dict', '_is_full_backward_hook', '_keep_in_fp32_modules', '_keys_to_ignore_on_load_unexpected', '_load_state_dict_post_hooks', '_load_state_dict_pre_hooks', '_modules', '_no_split_modules', '_non_persistent_buffers_set', '_parameters', '_state_dict_hooks', '_state_dict_pre_hooks', '_supports_gradient_checkpointing', '_version', 'attn_processors', 'call_super_init', 'class_embedding', 'config', 'config_name', 'device', 'dtype', 'dump_patches', 'encoder_hid_proj', 'has_compatibles', 'ignore_for_config', 'is_gradient_checkpointing', 'training']

full message here:

> Traceback (most recent call last):
  File "/home/haozong/projects/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/haozong/projects/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/node.py", line 217, in generate
    generation = pipeline.generate(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/ip_adapter/ip_adapter.py", line 803, in generate
    images = self.samples(
             ^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/ip_adapter/ip_adapter.py", line 755, in samples
    images = self.pipe(
             ^^^^^^^^^^
  File "/home/haozong/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/ip_adapter/ip_adapter.py", line 1049, in __call__
    else controlnet.nets[0].config.global_pool_conditions
         ^^^^^^^^^^^^^^^
  File "/home/haozong/anaconda3/envs/comfyui/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 155, in __getattr__
    return super().__getattr__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haozong/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ControlNetModel' object has no attribute 'nets'

**Comment by JayPritchet** [comment]
> Thanks for the great work!
> 
> When trying to use the ComfyUI version, I am not able to run the demo because of the following error:
> 
> > OSError: Error no file named config.json found in directory /home/haozong/projects/ComfyUI/custom_nodes/ComfyUI-StyleShot/prtrained_models/stable-diffusion-v1-5-archive.
> 
> I am using python 3.8 as in the original StyleShot enviroment and install all the requirements in both repositories (origin + ComfyUI).
> 
> Could you help me with that?

Hi! I met the same issue.
Then I changed the base model path in node.py from `base_model_path = "Comfy-Org/stable-diffusion-v1-5-archive"` to ` base_model_path = "ashllay/stable-diffusion-v1-5-archive"`
and then download some models that are missing from [stable-diffusion-v1-5/stable-diffusion-v1-5](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/tree/main)
And this worked for me.
Hope this will help you.

**Comment by neverbiasu** [comment]
thx, I will fix it now
